# Set theme
remote_theme: daviddarnes/alembic@main

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://kim-dg.github.io'
baseurl: '/blog'
title: 'KDG Blog'
description: 'This is my new website'
permalink: pretty
logo: "/assets/logos/logo@32px.png"

# Pagination
paginate: 5
paginate_path: blog/page:num
 
# Header nav
navigation_header:
- title: Home
  url: /
- title: About
  url: /about/
- title: Develop
  url: /develop/
- title: Music
  url: /music/
- title: Categories
  url: /categories/
- title: Search
  url: /search/

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Develop Posts
    output: true
    description: "develop My thoughts and ideas"
    feature_text: |
      Develop
    feature_image: "https://picsum.photos/2560/600?image=866"
  mu_posts:
    title: Music Posts
    output: true
    description: "music My thoughts and ideas"
    feature_text: |
      Music
    feature_image: "https://picsum.photos/2560/600?image=866"


# Collection settings
defaults:
  -
    scope:
      path: "Develop"
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: "Music"
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
