# Set theme
remote_theme: daviddarnes/alembic@main

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://kim-dg.github.io'
baseurl: '/blog'
title: 'KDG Blog'
description: 'This is my new website'
permalink: pretty
logo: "/assets/logos/logo@32px.png"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: About
  url: /about/
- title: Develop
  url: /develop/
- title: Project
  url: /project/
- title: Android
  url: /android/
- title: CS
  url: /cs/
- title: Life
  url: /life/
- title: Categories
  url: /categories/
- title: Search
  url: /search/

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Develop Posts
    output: true
    description: "develop"
    feature_text: |
      Develop
    feature_image: "https://picsum.photos/2560/600?image=866"
  project_posts:
    title: Project Posts
    output: true
    description: "project"
    feature_text: |
      Project
    feature_image: "https://picsum.photos/2560/600?image=866"
  android_posts:
    title: Android Posts
    output: true
    description: "android"
    feature_text: |
      Android
    feature_image: "https://picsum.photos/2560/600?image=866"
  cs_posts:
    title: CS Posts
    output: true
    description: "cs"
    feature_text: |
      CS
    feature_image: "https://picsum.photos/2560/600?image=866"
  life_posts:
    title: Life Posts
    output: true
    description: "life"
    feature_text: |
      Life
    feature_image: "https://picsum.photos/2560/600?image=866"
    


# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
